version: '3.9'

services:
  db:
    image: leandrocgsi/rest-react-dotnet-server-db
    command: mysqld --default_authentication_plugin=caching_sha2_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_with_asp_net_udemy
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - erudio-network

  rest-react-dotnet-server:
    image: leandrocgsi/rest-react-dotnet-server
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MySQLConnection__MySQLConnectionString: "Server=db;Port=3308;DataBase=rest_with_asp_net_udemy;Uid=docker;Pwd=docker"
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ASPNETCORE_HTTPS_PORTS: 8081
    ports:
      - 4430:8080
      - 44300:8081
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - db
    networks:
      - erudio-network
networks:
  erudio-network:
    driver: bridge
